// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var state = State.FromJson(jsonString);

using Newtonsoft.Json;

namespace QuickType
{
    internal class Converter
    {
        public static JsonConverter[] Settings { get; internal set; }
    }
}